### ISSUE TITLE
Remove jittering during slide animations

### ISSUE THREAD

**Issue by ProLoser** [ProLoser/ElegantAccordion#2]
The right-most edge of the slides jitters when animating, this jitter occasionally causes the slides to extend beyond the constraints of the container (causing them to pop down below). This really needs to be removed.

**Comment by brianraymes** [comment]
Any chance there has been an update on this issue?

**Comment by ProLoser** [comment]
Haven't had a chance lately. I'll try to look into it today.

**Comment by ProLoser** [comment]
This should be somewhat addressed in the latest commit. There is still a small gap that occasionally appears, but the slides should no longer jump down to the next row.
