### ISSUE TITLE
Show on click, then Hide all and show on click?

### ISSUE THREAD

**Issue by wdcsam** [ProLoser/ElegantAccordion#7]
Hi

I've tried to get this working on a click event so it could hopefully be used on mobile devices. Toggle works to a degree but you have to click it again to hide it. The beauty of this is that the second hover state, what I would call the 'rollout' hides the active pane. 

I am new to jquery and am reading through the sitepoint book at present and am really getting to grips with it - but this modification just seems a step to far for my simple mind!

How could the code be modified to work on a click??

Any tips or pointers most welcome

Cheers

**Comment by ProLoser** [comment]
I got ahold of an ipad and it seems to function properly (albeit laggy).

I'm a bit confused as to what functionality you want. You just want to be able to click on a panel?

Or do you want the panels to return to neutral after a certain amount of time?

**Comment by wdcsam** [comment]
Hi,

Thanks for getting back so quickly.

Sorry totally my mistake then, I assumed it wouldnt work as the jquery
works on a hover, which as I understood ios couldnt interperate... Sorry im
on android galaxy s... Its time like this I realise I need to buy an
iphone/pad!

Will test it in the applestore tomorrow... I may have just wasted 5 nights
for no reason. The lesson for me here is to test!

Thanks again for your prompt response and taking the time to get back to
me, you are very kind. Apologies if ive wasted your time.

I may just pop you a quick email tomorrow (its 00:51 here now) once ive
been to the applestore to let you know

Many thanks

Sam
On Nov 15, 2011 12:37 AM, "Dean Sofer" <
reply@reply.github.com>
wrote:

**Comment by ProLoser** [comment]
I added extra functionality:

When you call $(selector).eAccordion(); on an existing accordion (that has ALREADY been loaded) without passing a slide #, it will go to neutral state.

If you want to setup a timer so that after x amount of seconds after clicking, the accordion returns to neutral state you can do the following:

```
// Adds a second bind to the list-item click events
$('.accordion li').click(function(){ 
    setTimeout(function(){ 
        // Goes to neutral state after the countdown expires
        $('.accordion').eAccordion();
    }, 2000);
});
```

You should be able to use this to code whatever functionality you desire, as this is just an example.

**Comment by ProLoser** [comment]
IOS (and I think most mobile OS) 'simulate' the hover event when you
click. In other words, if there is a hover event binded, but no click
event, then the hover event is fired, although this looks strange (in
most situations) on a mobile device, it at least adds a degree of
backwards compatibility.

However, there is code in the accordion for both Hover AND click. When
you hover, it expands the section, but when you click, it keeps that
section open when you mouse out, at least until you mouseover another
slide (at which point normal behavior resumes).

Personally, my biggest concerns around mobile development is actually
fluidity of animation. Instead of using jQuery animations, I want to
do research into the plausibility of CSS3 animations
(transforms/transitions). When you use CSS3, the video card is
leveraged to power the animations instead of just the CPU (as with JS
animations). This makes an astounding difference in smoothness on
mobile devices, since they have a strong GPU but weak CPU.

On Mon, Nov 14, 2011 at 4:52 PM, wdcsam
reply@reply.github.com
wrote:

**Comment by ProLoser** [comment]
Can you close this ticket if it's no longer relevant?

**Comment by wdcsam** [comment]
Yeah ive only just started to see these css3 transitions, altho they've
probably been around a long time. Actually started googling pure css3
accordion late last night.. Theres some out there from 2008. Im a little
behind!

I should get to grips with the css a little quicker, the syntax of css is
so simple and its something ive got a good grasp of already. Need to get a
book on 3 tho urgently.Really must read more on jquery... Any tips? Im
reading thru novice to ninja.. Im like a fat yellow belt at the minute.
Does the knowledge just come with knowledge/experience/time?

Thanks again for your help - and a beautiful solution!!
On Nov 15, 2011 1:05 AM, "Dean Sofer" <
reply@reply.github.com>
wrote:

**Comment by ProLoser** [comment]
ALL of my knowledge came from hanging out on IRC talking to a lot of the
core devs whenever I got stuck. Even if people are too busy to answer your
questions or help you, you'll almost always find someone who can point you
in the right direction. Checkout irc://irc.freenode.net/jquery or go to
webchat.freenode.net and join the #jquery channel

On Tuesday, November 15, 2011, wdcsam wrote:

> Yeah ive only just started to see these css3 transitions, altho they've
> probably been around a long time. Actually started googling pure css3
> accordion late last night.. Theres some out there from 2008. Im a little
> behind!
> 
> I should get to grips with the css a little quicker, the syntax of css is
> so simple and its something ive got a good grasp of already. Need to get a
> book on 3 tho urgently.Really must read more on jquery... Any tips? Im
> reading thru novice to ninja.. Im like a fat yellow belt at the minute.
> Does the knowledge just come with knowledge/experience/time?
> 
> Thanks again for your help - and a beautiful solution!!
> On Nov 15, 2011 1:05 AM, "Dean Sofer" <
> reply@reply.github.com javascript:;>
> wrote:
> 
> > IOS (and I think most mobile OS) 'simulate' the hover event when you
> > click. In other words, if there is a hover event binded, but no click
> > event, then the hover event is fired, although this looks strange (in
> > most situations) on a mobile device, it at least adds a degree of
> > backwards compatibility.
> > 
> > However, there is code in the accordion for both Hover AND click. When
> > you hover, it expands the section, but when you click, it keeps that
> > section open when you mouse out, at least until you mouseover another
> > slide (at which point normal behavior resumes).
> > 
> > Personally, my biggest concerns around mobile development is actually
> > fluidity of animation. Instead of using jQuery animations, I want to
> > do research into the plausibility of CSS3 animations
> > (transforms/transitions). When you use CSS3, the video card is
> > leveraged to power the animations instead of just the CPU (as with JS
> > animations). This makes an astounding difference in smoothness on
> > mobile devices, since they have a strong GPU but weak CPU.
> > 
> > On Mon, Nov 14, 2011 at 4:52 PM, wdcsam
> > <reply@reply.github.com <javascript:;>>
> > wrote:
> > 
> > > Hi,
> > > 
> > > Thanks for getting back so quickly.
> > > 
> > > Sorry totally my mistake then, I assumed it wouldnt work as the jquery
> > > works on a hover, which as I understood ios couldnt interperate...
> > > Sorry
> > > im
> > > on android galaxy s... Its time like this I realise I need to buy an
> > > iphone/pad!
> > > 
> > > Will test it in the applestore tomorrow... I may have just wasted 5
> > > nights
> > > for no reason. The lesson for me here is to test!
> > > 
> > > Thanks again for your prompt response and taking the time to get back
> > > to
> > > me, you are very kind. Apologies if ive wasted your time.
> > > 
> > > I may just pop you a quick email tomorrow (its 00:51 here now) once ive
> > > been to the applestore to let you know
> > > 
> > > Many thanks
> > > 
> > > Sam
> > > On Nov 15, 2011 12:37 AM, "Dean Sofer" <
> > > reply@reply.github.com javascript:;>
> > > wrote:
> > > 
> > > > I got ahold of an ipad and it seems to function properly (albeit
> > > > laggy).
> > > > 
> > > > I'm a bit confused as to what functionality you want. You just want to
> > > > be
> > > > able to click on a panel?
> > > > 
> > > > Or do you want the panels to return to neutral after a certain amount
> > > > of
> > > > time?
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ProLoser/ElegantAccordion/issues/7#issuecomment-2739191
> > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ProLoser/ElegantAccordion/issues/7#issuecomment-2739318
> > 
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ProLoser/ElegantAccordion/issues/7#issuecomment-2739432
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ProLoser/ElegantAccordion/issues/7#issuecomment-2742076

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by wdcsam** [comment]
Cool! Thanks dean you're a legend.
On Nov 15, 2011 9:37 AM, "Dean Sofer" <
reply@reply.github.com>
wrote:
